### ISSUE TITLE
SSI- review hardcoded context

### ISSUE THREAD

**Issue by fkim7** [knox-networks/ssi#122] opened 2023-03-01 15:38 UTC
[/src/identity.rs](https://github.com/knox-networks/ssi/pull/121/files/176f286a43fc174fc2899fbd11b135244f2133a3#diff-4ef9da87778def7bb67a144d06f9cc429d901994dd8b054812c14c1dac2b0df6)
        context: vec![
            "https://www.w3.org/ns/did/v1".to_string(),
            "https://w3id.org/security/suites/ed25519-2020/v1".to_string(),
        ],

@sKudryashov @LuisOsta Can we move these URLs out of the code and at least into a config file? we can have a separate ticket for this outside of this PR but if the URL changes we'd have to update the builds/images and deliver new helm charts to all customers instead of our professional services team/customer team be able to make some updates by configuration. Or maybe since SSI is shipped as an open source library its less of a concern compared to applications?

**Comment by LuisOsta** [comment] 2023-11-17 20:40
Closing as duplicate of #112

**Closed by LuisOsta** 2023-11-17 20:40 UTC
